### ISSUE TITLE
[BUG] I cannot compile the discord bot

### ISSUE THREAD

**Issue by claimholder** [lukazbaum/discordjs-command-handler#1]
Whenever i try "compiling" the handler, this is the error I get:

'rm' is not recognized as an internal or external command,
operable program or batch file.

pls fix it
thanks

**Comment by lukazbaum** [comment]
Hello,
sorry for the late response.
Which operating system are you using?
If it's windows replace this line in the package.json:

```json
"clean": "rm -rf dist",
```
with
```json
"clean": "del -f \"dist*\"",
```
