### ISSUE TITLE
[IMPROVEMENT]: prefix command change to allow whitespace 

### ISSUE THREAD

**Issue by jbasalone** [lukazbaum/discordjs-command-handler#2]
**Describe Your Suggestion or Improvement**
Prefix string only takes in literal characters. coding or adding a whitespace in the prefix string gets ignored. 

**Code Segment (if applicable)**
I was unable to find where this happens. In the command helper it takes in [0] which should include the white space. 

**Benefits**
prefix commands are very popular in the discord server im in and testing this out for. The code is awesome! but for example you have "!" as a prefix command but multiple bots use this prefix. So being able to change it and not have something like 
prefix ="pm" and takes in "pmpong" 
vs "pm pong" would allow for for more intentional usability. I wold SUPER appreciate if you could help find how to account for white space or address it in code. 

**Potential Drawbacks**
not to expect a white space but to allow it

**Would you like to work on this improvement?**
- [ x] Yes
- [ ] No

**Comment by lukazbaum** [comment]
Hello,
thank you for opening an issue.

The error you are referring to happens in this [file](https://github.com/lukazbaum/discordjs-command-handler/blob/e5f7fb3bac6f5b48a08a4a6f9c7606866600adf6/src/handler/util/handleChatCommands.ts) at line 15.

You can replace this line with:
```ts
const matches = prefix.match(/\s/g);
const whitespaceAmount: number = matches ? matches.length : 0;
const messageCommand: string = message.content.split(" ")[whitespaceAmount].replace(prefix, "");
```
or download the newest version to fix your issue.
If you have any more questions/suggestions feel free to ask ^^

**Comment by jbasalone** [comment]
Awesome! grabbed the latest.
