### ISSUE TITLE
Add command security control for categories 

### ISSUE THREAD

**Issue by jbasalone** [lukazbaum/discordjs-command-handler#5]
## Feature Description
Category Whitelist so that all channels are authorized under that parentID to execute commands. 

## Problem and Motivation
Channels are organized in some discord servers by category and have limited access to functionality. If a new channel is made in this category, the white list for all commands have to be updated. Or all channels are whitelisted and special auth will have to grated in each command. 

## Proposed Solution
update the handler(s)

## Alternatives Considered
in code look ups for parentID  for each user initiating the command

**Comment by lukazbaum** [comment]
Hello,
thanks for suggesting a feature.

I added category whitelists and blacklists in the [newest commit](https://github.com/lukazbaum/discordjs-command-handler/commit/51f9733b7334154ec54b91f2f98c64bc81bfacd9).

**Comment by jbasalone** [comment]
omg thank you!
