### ISSUE TITLE
[SUPPORT]: Channel Whitelisting  Ignores Category Whitelist 

### ISSUE THREAD

**Issue by jbasalone** [lukazbaum/discordjs-command-handler#6]
**Describe Your Question or Issue**

It appears when you add both channelWhitelist and categoryWhitelist the first takes precedence. I didnt file a bug cause I thought maybe this might be intentional. 

**What Have You Tried?**
adding and removing cannel/category whitelisting. When I have both the first in order is authorized. 

**Expected Behavior**
Not so much expected but should it allow both or just one 

**Screenshots/Code Snippets**

**Environment (please complete the following information):**
- OS: Linux
- Discord Bot Handler Version: Latest
- Node.js Version: v20.12.2
- Discord.js Version: 14.15.3

**Comment by lukazbaum** [comment]
Hello,

All whitelist conditions must be met for the command to be executed. However, if you prefer the command to execute when any one of the optional whitelist conditions is met, you can use the newly added [optional whitelists](https://github.com/lukazbaum/discordjs-command-handler?tab=readme-ov-file#%EF%B8%8F-command-arguments).

Please provide a code example of the problem mentioned above.

**Comment by jbasalone** [comment]
OH . you are so cool.  I removed it in favor for one or the other channel or category whitelists. With both listed at the same time it didnt honor either. But now with optional.... I have ALL THE Power.

**Comment by lukazbaum** [comment]
Does this fix your problem?

**Comment by jbasalone** [comment]
```
export = {
    name: "assign",
    aliases: ["Assign", "ac","assignchannel", "assignch"],
    type: CommandTypes.PrefixCommand,
    roleWhitelist:["1148992217202040942"],
    channelWhitelist:["1142401741866946702","1147233774938107966", "1138531756878864434", "1151411404071518228","1142401741866946702"],
    optionalCategoryWhitelist:["1137072690264551604"],
```

do both need to be optional? I dont think its working :( No logs.

**Comment by lukazbaum** [comment]
The current command setup requires all the following conditions to be met for execution:

    You have the role: "1148992217202040942"
    You are in one of these channels: "1142401741866946702", "1147233774938107966", "1138531756878864434", "1151411404071518228", "1142401741866946702"
    The channels is in this category: "1137072690264551604"

If you want the command to execute when any one of these conditions is met, you need to make all whitelists optional.
Standard whitelists require all specified conditions to be met for the command to execute, while optional whitelists only require one of all optional whitelist conditions to be met.

**Comment by jbasalone** [comment]
thank you
